### ISSUE TITLE
Train/valid/test split

### ISSUE THREAD

**Issue by fmellomascarenhas** [OpenBioLink/OpenBioLink#67]
Hi all,

I have been analyzing the HQ directed split and found some interesting events:
1) There are 26 loop edges (id connect to itself);
2) 215,278 edges do not belong to train/valid/test split;
3) 118,355 node pairs, (ex: Doesn't matter if it is [a,b] or [b,a]) have edges (505,162) in more than one split, such as train and valid.
4) Considering all of the edges, there is a subgraph of 50 nodes disconnected from the main graph;
5) The train set apparently has 168 disconnected subgraphs. 167 with average size of 3.8 nodes, and 1 big subgraph with 180k nodes;

I will work on my own split, probably using node pairs as criteria, to avoid data leakage. I wonder if, based on your experience, there is something else I should worry about when using this approach. I could think of:
- Disconnected nodes;
- Leaks like: If drug -> treats -> disease and drug -> targets -> gene, then it could be trivial that gene -> causes > disease;
- Not using available information between two nodes during inference;

thanks!

**Comment by nomisto** [comment]
Hi @fmellomascarenhas,

Sorry for the late response and thanks for sharing your analyzation! We are currently also investigating issues with our filtering method, so this is very helpful.

To 2. these edges are missing in the split as a result of our filtering, see [here](https://github.com/OpenBioLink/OpenBioLink#user-content-train-test-set-post-processing). We filtered inverses a -> b, b -> a, as well as "super"-relations a drug_bind_gene b, b gene_drug a. So it is no surprise that there are still edges with the same node pairs f.e. a drug_bind_gene b, a drug_activation_gene b, but as you can see these two example edges are still closely related so a filtering based on node pairs might work well.

That depends on your usage. Since OpenBioLink aims to be a benchmark dataset, one concern with filtering is that you generally have to be aware of how your construction priniciple could affect different approaches. Otherwise there can be approaches that exploit the filtering method (f.e. recognize patterns based on the validation set) or approaches that have a disadvantage due to our filtering method (more than others).

**Comment by fmellomascarenhas** [comment]
Hi @nomisto, thanks for answering! Regarding #2, I believe that I got it after the filtering. With the data comes a **stats** table that shows the amount of edges before and after the filters. If I remember correctly, the number of edges I am checking matches the number of edges after filtering, but I will double check to make sure if what I am saying makes sense.

**Comment by nomisto** [comment]
No problem! Closing this for now
